from datetime import time

START_SESSION_HOUR = 16
START_SESSION_MINUTE = 30

TOLLERANCE_SECOND =30
INTERVAL_MINUTES = 5

END_SESSION_HOUR = 22
END_SESSION_MINUTE = 58

START_SESSION = time(START_SESSION_HOUR, START_SESSION_MINUTE)
END_SESSION = time(END_SESSION_HOUR, END_SESSION_MINUTE)

##GENERAL VARIABLES
open_positions = {}
trade_count_per_stock = {}
MAX_DAILY_TRADES = 10
MAX_TRADES_PER_STOCK = 1

FIXED_CAPITAL = 50000
CAPITAL_FOR_TRADE = FIXED_CAPITAL/MAX_DAILY_TRADES
